import moment from "moment";

export const profile = {
  languages: [
    "Afrikaans",
    "Albanian",
    "Amharic",
    "Arabic",
    "Aramaic",
    "Armenian",
    "Assamese",
    "Aymara",
    "Azerbaijani",
    "Balochi",
    "Bamanankan",
    "Bashkort (Bashkir)",
    "Basque",
    "Belarusan",
    "Bengali",
    "Bhojpuri",
    "Bislama",
    "Bosnian",
    "Brahui",
    "Bulgarian",
    "Burmese",
    "Cantonese",
    "Catalan",
    "Cebuano",
    "Chechen",
    "Cherokee",
    "Croatian",
    "Czech",
    "Dakota",
    "Danish",
    "Dari",
    "Dholuo",
    "Dutch",
    "English",
    "Esperanto",
    "Estonian",
    "Finnish",
    "French",
    "Georgian",
    "German",
    "Gikuyu",
    "Greek",
    "Guarani",
    "Gujarati",
    "Haitian Creole",
    "Hausa",
    "Hawaiian",
    "Hawaiian Creole",
    "Hebrew",
    "Hiligaynon",
    "Hindi",
    "Hungarian",
    "Icelandic",
    "Igbo",
    "Ilocano",
    "Indonesian (Bahasa Indonesia)",
    "Inuit/Inupiaq",
    "Irish Gaelic",
    "Italian",
    "Japanese",
    "Jarai",
    "Javanese",
    "Kabyle",
    "Kannada",
    "Kashmiri",
    "Kazakh",
    "Khmer",
    "Khoekhoe",
    "Korean",
    "Kurdish",
    "Kyrgyz",
    "Lao",
    "Latin",
    "Latvian",
    "Lingala",
    "Lithuanian",
    "Macedonian",
    "Maithili",
    "Malagasy",
    "Malay (Bahasa Melayu)",
    "Malayalam",
    "Mandarin (Chinese)",
    "Marathi",
    "Mende",
    "Mongolian",
    "Nahuatl",
    "Navajo",
    "Nepali",
    "Norwegian",
    "Ojibwa",
    "Oriya",
    "Oromo",
    "Pashto",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Quechua",
    "Romani",
    "Romanian",
    "Russian",
    "Rwanda",
    "Samoan",
    "Sanskrit",
    "Serbian",
    "Shona",
    "Sindhi",
    "Sinhala",
    "Slovak",
    "Slovene",
    "Somali",
    "Spanish",
    "Swahili",
    "Swedish",
    "Tachelhit",
    "Tagalog",
    "Tajiki",
    "Tamil",
    "Tatar",
    "Telugu",
    "Thai",
    "Tibetic languages",
    "Tigrigna",
    "Tok Pisin",
    "Turkish",
    "Turkmen",
    "Ukrainian",
    "Urdu",
    "Uyghur",
    "Uzbek",
    "Vietnamese",
    "Warlpiri",
    "Welsh",
    "Wolof",
    "Xhosa",
    "Yakut",
    "Yiddish",
    "Yoruba",
    "Yucatec",
    "Zapotec",
    "Zulu",
  ],
  skills: [
    "presentation",
    "Communication",
    "Teamwork",
    "Writing",
    "conversation",
    "Effective communication",
    "Teamwork",
    "Responsibility",
    "Creativity",
    "Problem-solving",
    "Leadership",
    "Extroversion",
    "People skills",
    "Openness",
    "Adaptability",
    "Effective communication",
    "Emotional intelligence",
    "Conflict management",
    "Teamwork skills",
    "Stress management",
    "Problem-solving",
    "Productivity & organization",
    "Critical thinking",
    "Attention to detail",
    "Adaptability Time managemen",
  ],
  states: [
    "Alexandria",
    "Aswan",
    "Asyut",
    "Beheira",
    "Beni Suef",
    "Cairo",
    "Dakahlia",
    "Damietta",
    "Faiyum",
    "Gharbia",
    "Giza",
    "Ismailia",
    "Kafr El Sheikh",
    "Luxor",
    "Matruh",
    "Minya",
    "Monufia",
    "New Valley",
    "North Sinai",
    "Port Said",
    "Qalyubia",
    "Qena",
    "Red Sea",
    "Sharqia",
    "Sohag",
    "South Sinai",
    "Suez",
  ],
  countries: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Côte d'Ivoire",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia (Czech Republic)",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini (fmr. 'Swaziland')",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",

    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (formerly Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ],
};

export const availableLanguages = [
  {
    name: "English",
    value: "en",
  },
  {
    name: "Spanish",
    value: "sp",
  },
  {
    name: "French",
    value: "fr",
  },
  {
    name: "German",
    value: "ge",
  },
  {
    name: "Italian",
    value: "it",
  },
  {
    name: "Brazilian",
    value: "br",
  },
  {
    name: "Chinese",
    value: "ch",
  },
  {
    name: "Dutch",
    value: "du",
  },
  {
    name: "Japanese",
    value: "ja",
  },
  {
    name: "Latin",
    value: "la",
  },
  {
    name: "Polish",
    value: "po",
  },
  {
    name: "Russian",
    value: "ru",
  },
];

export const comp_reg = {
  quizTime: 60 * 1000 * 60, //ms
};

const currentYear = moment().get("year");
const years = [];
for (let i = currentYear; i > currentYear - 50; i--) {
  years.push(i);
}

export const yearsToPick = years;
export const monthsToPick = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "June",
  "July",
  "Aug",
  "Sept",
  "Oct",
  "Nov",
  "Dec",
];

export const langNameConverter = {
  en: "English", //
  sp: "Spanish", //
  fr: "French", //
  ge: "German", //
  it: "Italian", //
  br: "Brazilian", //----//
  ch: "Chinese", //
  du: "Dutch", //
  ja: "Japanese", //
  la: "Latin", //
  po: "Polish", //
  ru: "Russian", //
};
